//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class SplashScreen : MonoBehaviour
{
	public enum eFadeState {FADE_IN = 0, FADE_DUR = 1, FADE_OUT = 2};
	public eFadeState fadeState = eFadeState.FADE_IN;
	public bool skip = false;
	public float fadeIn = 0.0f;
	public float fadeOut = 0.0f;
	public float duration = 0.0f;

	private SkeletonAnimation skeletonAnimation;

	public bool animIsPlaying = false;
	public bool animIsDone = false;


	void Start()
	{
		skeletonAnimation = GetComponent<SkeletonAnimation>();
		if (skeletonAnimation != null)
		{
			skeletonAnimation.state.Start += startAnimListener;
			skeletonAnimation.state.End += endAnimListener;
		}
	}

	public void Play()
	{
		if (skeletonAnimation != null && animIsPlaying == false)
		{
			skeletonAnimation.timeScale = 0.65f;
			skeletonAnimation.state.SetAnimation(0,"animation",false);
		}
	}

	public int GetFadeState()
	{
		return (int)fadeState;
	}
	
	public void SetFadeStateIn()
	{
		fadeState = eFadeState.FADE_IN;
	}
	public void SetFadeStateOut()
	{
		fadeState = eFadeState.FADE_OUT;
	}
	public void SetFadeStateDur()
	{
		fadeState = eFadeState.FADE_DUR;
	}

	void startAnimListener(Spine.AnimationState state, int trackIndex)
	{
		animIsPlaying = true;
		animIsDone = false;
	}
	void endAnimListener (Spine.AnimationState state, int trackIndex)
	{
		animIsDone = true;
	}
}


