//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18408
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

public class Dialog
{
	[System.Serializable]
	public struct stPerson
	{
		public string uid;
		public int order_id;
		public string text;
		public int fade_in;
		public int fade_out;
		public string soundfile;
		public int click_away;
		public int help;
		public int duration;
	}
	public stPerson person;
	public List<stPerson> persons = new List<stPerson>();
	public string event_trigger;

	public Dialog ()
	{

	}
}


